#pragma once
#include <SFML/Graphics.hpp>
#include <cmath>
#include <vector>
#include <cstdlib>
#include <unordered_set>
#include "Core/Animation/AnimatedSprite.h"
#include "Core/Data/ProfileManager.h"

class EnemyBase;
class WeaponBase;

// A decoupled payload generated by Weapons. Handles its own movement and collision logic.
class Projectile {
public:
    Projectile() : m_active(false), m_damage(0), m_speed(0), m_knockbackForce(0), m_lifeTimer(0), m_lifetime(5.f), m_piercing(false) {}

    void init(const sf::Vector2f& startPos, const sf::Vector2f& direction, float damage, float speed, float range, float lifetime, bool piercing = false) {
        m_position = startPos;
        m_direction = direction;
        
        // Normalize direction
        float length = std::sqrt(m_direction.x * m_direction.x + m_direction.y * m_direction.y);
        if (length > 0) m_direction /= length;
        
        m_speed = speed * ProfileManager::GetInstance().getProjectileSpeedMultiplier();
        m_velocity = m_direction * m_speed;
        m_acceleration = sf::Vector2f(0.f, 0.f);
        m_damage = damage * ProfileManager::GetInstance().getMightMultiplier();
        m_knockbackForce = 0;
        m_lifetime = lifetime * ProfileManager::GetInstance().getDurationMultiplier();
        m_lifeTimer = 0.f;
        m_piercing = piercing;
        m_active = true;
        m_isEnemyProj = false;
        m_hasSprite = false;
        m_trailEnabled = false;
        m_trailTimer = 0.f;
        m_trailParticles.clear();
        m_gravity = 0.f;
        m_spinSpeed = 0.f;
        m_isGarlicAura = false;
        m_isOrbiting = false;
        m_orbitRadius = 0.f;
        m_orbitAngle = 0.f;
        m_orbitSpeed = 0.f;
        
        float areaMult = ProfileManager::GetInstance().getAreaMultiplier();
        m_shape.setRadius(5.f * areaMult);
        m_shape.setFillColor(sf::Color::Yellow);
        m_shape.setOrigin(5.f * areaMult, 5.f * areaMult);
        m_shape.setPosition(m_position);

        // Store rotation angle — will be applied when sprite is set
        m_initRotation = 0.f;
        if (length > 0) {
            m_initRotation = std::atan2(m_direction.y, m_direction.x) * 180.f / 3.14159f;
        }
    }

    // Set a static sprite frame from an already-loaded texture (shared by weapon)
    void setSprite(const sf::Texture& tex, const sf::IntRect& frame, float scale = 2.f, bool applyRotation = true, sf::Color color = sf::Color::White) {
        m_animSprite.setTexture(tex);
        m_animSprite.setFrames({ frame }, 8.f);
        m_animSprite.setOrigin(frame.width / 2.f, frame.height / 2.f);
        float areaMult = ProfileManager::GetInstance().getAreaMultiplier();
        m_animSprite.setScale(scale * areaMult, scale * areaMult);
        m_animSprite.setColor(color);
        if (applyRotation) m_animSprite.setRotation(m_initRotation);
        m_animSprite.setPosition(m_position);
        m_hasSprite = true;
        m_spriteColor = color;
        m_spriteScale = scale;
        m_spriteFrame = frame;
        m_spriteTex = &tex;
    }

    // Set an animated sprite (multiple frames) for things like the Whip swing
    void setAnimatedSprite(const sf::Texture& tex, const std::vector<sf::IntRect>& frames, float fps, float scale = 2.f) {
        if (frames.empty()) return;
        m_animSprite.setTexture(tex);
        m_animSprite.setFrames(frames, fps);
        m_animSprite.setAutoCenter(true); // Ensure origin is updated as frame sizes change
        m_animSprite.setOrigin(frames[0].width / 2.f, frames[0].height / 2.f);
        float areaMult = ProfileManager::GetInstance().getAreaMultiplier();
        m_animSprite.setScale(scale * areaMult, scale * areaMult);
        m_animSprite.setRotation(m_initRotation);
        m_animSprite.setPosition(m_position);
        m_hasSprite = true;
    }

    // Enable a sparkle trail. `spawnInterval` = seconds between trail particles (e.g. 0.03)
    // `particleLifetime` = how long each particle lives (e.g. 0.25)
    // `color` = trail particle tint
    void enableTrail(float spawnInterval = 0.04f, float particleLifetime = 0.2f, sf::Color color = sf::Color::White) {
        m_trailEnabled    = true;
        m_trailInterval   = spawnInterval;
        m_trailLifetime   = particleLifetime;
        m_trailColor      = color;
        m_trailTimer      = 0.f;
    }

    void setOrbiting(float radius, float startAngle, float speed) {
        m_isOrbiting = true;
        m_orbitRadius = radius;
        m_orbitAngle = startAngle;
        m_orbitSpeed = speed;
    }

    void update(float dt, const sf::Vector2f& playerPos = sf::Vector2f(0.f, 0.f), const sf::FloatRect& cameraBounds = sf::FloatRect()) {
        if (!m_active) return;

        if (m_isAura) {
            m_position = playerPos;
            m_velocity = sf::Vector2f(0.f, 0.f);
        } else if (m_isOrbiting) {
            m_orbitAngle += m_orbitSpeed * dt;
            m_position = playerPos + sf::Vector2f(std::cos(m_orbitAngle) * m_orbitRadius, std::sin(m_orbitAngle) * m_orbitRadius);
            m_velocity = sf::Vector2f(0.f, 0.f);
        } else {
            if (m_hasDelayedAccel && !m_accelTriggered) {
                m_accelTimer += dt;
                if (m_accelTimer >= m_accelTimeLimit) {
                    m_accelTriggered = true;
                    m_acceleration = m_delayedAcceleration;
                }
            }

            m_velocity += m_acceleration * dt;
            
            // Cap speed if maxSpeed is set
            if (m_maxSpeed > 0.f) {
                float currentSpeedSq = m_velocity.x * m_velocity.x + m_velocity.y * m_velocity.y;
                if (currentSpeedSq > m_maxSpeed * m_maxSpeed) {
                    float currentSpeed = std::sqrt(currentSpeedSq);
                    m_velocity = (m_velocity / currentSpeed) * m_maxSpeed;
                }
            }

            m_velocity.y += m_gravity * dt;
            m_position += m_velocity * dt;

            // Bouncing logic
            if (m_bounceOffScreen && cameraBounds.width > 0.f) {
                float left = cameraBounds.left;
                float right = cameraBounds.left + cameraBounds.width;
                float top = cameraBounds.top;
                float bottom = cameraBounds.top + cameraBounds.height;
                
                if (m_position.x < left && m_velocity.x < 0) {
                    m_position.x = left;
                    m_velocity.x = -m_velocity.x;
                } else if (m_position.x > right && m_velocity.x > 0) {
                    m_position.x = right;
                    m_velocity.x = -m_velocity.x;
                }
                
                if (m_position.y < top && m_velocity.y < 0) {
                    m_position.y = top;
                    m_velocity.y = -m_velocity.y;
                } else if (m_position.y > bottom && m_velocity.y > 0) {
                    m_position.y = bottom;
                    m_velocity.y = -m_velocity.y;
                }
            }

            // Landing logic for thrown projectiles like Santa Water
            if (m_isLanding && m_position.y >= m_landingY && m_velocity.y > 0.f) {
                m_position.y = m_landingY;
                m_velocity = sf::Vector2f(0.f, 0.f);
                m_gravity = 0.f;
                m_isLanding = false;
                m_hasLanded = true;
                
                // Change sprite to puddle if needed
                if (m_landedSpriteTex) {
                    if (m_isLandedAnimated && !m_landedSpriteFrames.empty()) {
                        setAnimatedSprite(*m_landedSpriteTex, m_landedSpriteFrames, m_landedAnimFps, m_landedSpriteScale);
                        m_animSprite.setColor(m_spriteColor);
                        m_animSprite.setLooping(false); // Play exactly once over its lifetime
                    } else {
                        setSprite(*m_landedSpriteTex, m_landedSpriteFrame, m_landedSpriteScale, false, m_spriteColor);
                    }
                }
            }
        }
        
        // Hit interval for continuous damage
        if (m_hitInterval > 0.f && !m_isLanding) {
            m_hitIntervalTimer += dt;
            if (m_hitIntervalTimer >= m_hitInterval) {
                m_hitIntervalTimer = 0.f; // The wiki says they reset simultaneously
                m_hitEnemies.clear();
            }
        }
        
        m_shape.setPosition(m_position);
        if (m_useRect) m_rectShape.setPosition(m_position);
        if (m_hasSprite) {
            if (m_spinSpeed != 0.f) {
                m_initRotation += m_spinSpeed * dt;
                m_animSprite.setRotation(m_initRotation);
            }
            m_animSprite.setPosition(m_position);
            m_animSprite.update(dt);
        }
        
        // Spawn trail particles
        if (m_trailEnabled) {
            m_trailTimer += dt;
            while (m_trailTimer >= m_trailInterval) {
                m_trailTimer -= m_trailInterval;
                TrailParticle tp;
                // Slight random offset around current position
                float ox = ((std::rand() % 100) - 50) * 0.03f;
                float oy = ((std::rand() % 100) - 50) * 0.03f;
                tp.pos      = m_position + sf::Vector2f(ox, oy);
                tp.life     = m_trailLifetime;
                tp.maxLife  = m_trailLifetime;
                tp.scale    = m_spriteScale * 0.6f;   // start at 60% of main sprite scale
                m_trailParticles.push_back(tp);
            }
        }

        // Age and cull trail particles
        for (auto& tp : m_trailParticles) {
            tp.life -= dt;
        }
        m_trailParticles.erase(
            std::remove_if(m_trailParticles.begin(), m_trailParticles.end(),
                [](const TrailParticle& tp){ return tp.life <= 0.f; }),
            m_trailParticles.end());

        m_lifeTimer += dt;
        if (m_lifeTimer >= m_lifetime) {
            m_active = false;
        }
    }

    void draw(sf::RenderWindow& window) {
        if (!m_active) return;

        // Draw trail particles first (behind main sprite)
        if (m_trailEnabled && m_spriteTex && !m_trailParticles.empty()) {
            sf::Sprite trailSprite;
            trailSprite.setTexture(*m_spriteTex);
            trailSprite.setTextureRect(m_spriteFrame);
            trailSprite.setOrigin(m_spriteFrame.width / 2.f, m_spriteFrame.height / 2.f);

            for (const auto& tp : m_trailParticles) {
                float t = tp.life / tp.maxLife;       // 1 = fresh, 0 = dead
                float alpha  = 200.f * t;              // fade out
                float scale  = tp.scale * t;           // shrink as it fades
                
                sf::Color c = m_trailColor;
                c.a = static_cast<sf::Uint8>(std::max(0.f, alpha));

                trailSprite.setColor(c);
                trailSprite.setScale(scale, scale);
                trailSprite.setPosition(tp.pos);
                window.draw(trailSprite, sf::BlendAdd); // additive blending = glowing
            }
        }

        // Draw main projectile
        if (m_hasSprite) {
            m_animSprite.draw(window);
        } else if (m_useRect) {
            window.draw(m_rectShape);
        } else {
            if (m_isGarlicAura) {
                // Faint yellow background
                m_shape.setFillColor(sf::Color(255, 255, 200, 40));
                m_shape.setOutlineThickness(0.f);
                window.draw(m_shape);

                // Pulsating concentric rings
                float maxRadius = m_shape.getRadius();
                float timer = m_lifeTimer * 1.5f;
                for (int i = 0; i < 4; ++i) {
                    float phase = std::fmod(timer + i * 0.25f, 1.0f);
                    float r = maxRadius * phase;
                    if (r <= 0.1f) continue;
                    
                    sf::CircleShape ring(r);
                    ring.setOrigin(r, r);
                    ring.setPosition(m_shape.getPosition());
                    ring.setFillColor(sf::Color::Transparent);
                    ring.setOutlineThickness(2.f);
                    
                    float alpha = 150.f * (1.0f - phase);
                    ring.setOutlineColor(sf::Color(255, 255, 255, static_cast<sf::Uint8>(alpha)));
                    window.draw(ring);
                }
            } else {
                window.draw(m_shape);
            }
        }
    }

    bool isActive() const { return m_active; }
    void deactivate() { m_active = false; }
    bool isPiercing() const { return m_piercing; }
    
    bool canHit() const {
        return m_active && (!m_isLanding);
    }
    
    void setBounceOffScreen(bool bounce) { m_bounceOffScreen = bounce; }
    
    float getDamage() const { return m_damage; }
    float getKnockback() const { return m_knockbackForce; }
    void setKnockback(float force) { m_knockbackForce = force; }
    sf::FloatRect getBounds() const { 
        if (m_hasSprite) return m_animSprite.getGlobalBounds();
        if (m_useRect) return m_rectShape.getGlobalBounds();
        return m_shape.getGlobalBounds(); 
    }
    sf::Vector2f getPosition() const { return m_position; }
    sf::Vector2f getDirection() const { return m_direction; }

    void setCustomShape(const sf::Vector2f& size, sf::Color color) {
        // Switch to a rectangle for things like Whip (when no sprite)
        float areaMult = ProfileManager::GetInstance().getAreaMultiplier();
        sf::Vector2f scaledSize = size * areaMult;
        m_rectShape.setSize(scaledSize);
        m_rectShape.setFillColor(color);
        m_rectShape.setOrigin(scaledSize.x / 2.f, scaledSize.y / 2.f);
        m_useRect = true;
    }

    void setCircleShape(float radius, sf::Color color) {
        float areaMult = ProfileManager::GetInstance().getAreaMultiplier();
        float scaledRadius = radius * areaMult;
        m_shape.setRadius(scaledRadius);
        m_shape.setFillColor(color);
        m_shape.setOrigin(scaledRadius, scaledRadius);
        m_useRect = false;
    }

    void setGravity(float g) { m_gravity = g; }
    void setSpinSpeed(float s) { m_spinSpeed = s; }
    void setAcceleration(const sf::Vector2f& acc) { m_acceleration = acc; }
    void setVelocity(const sf::Vector2f& vel) { m_velocity = vel; }

    bool isEnemyProj() const { return m_isEnemyProj; }
    void setEnemyProj(bool isEnemy) { m_isEnemyProj = isEnemy; }
    void setFillColor(const sf::Color& color) { 
        m_shape.setFillColor(color); 
        m_rectShape.setFillColor(color);
    }
    
    void setOutline(float thickness, const sf::Color& color) {
        m_shape.setOutlineThickness(thickness);
        m_shape.setOutlineColor(color);
        m_rectShape.setOutlineThickness(thickness);
        m_rectShape.setOutlineColor(color);
    }

    void setIsAura(bool isAura) { m_isAura = isAura; }
    void setGarlicAura(bool garlic) { m_isGarlicAura = garlic; }

    void setSourceWeapon(WeaponBase* weapon) { m_sourceWeapon = weapon; }
    WeaponBase* getSourceWeapon() const { return m_sourceWeapon; }

    bool hasHitEnemy(EnemyBase* enemy) const {
        return m_hitEnemies.find(enemy) != m_hitEnemies.end();
    }
    
    void addHitEnemy(EnemyBase* enemy) {
        m_hitEnemies.insert(enemy);
    }

    void setMaxSpeed(float maxSpeed) {
        m_maxSpeed = maxSpeed;
    }

    void setDelayedAcceleration(const sf::Vector2f& acc, float delayTime) {
        m_hasDelayedAccel = true;
        m_delayedAcceleration = acc;
        m_accelTimeLimit = delayTime;
        m_accelTimer = 0.f;
        m_accelTriggered = false;
    }

    void setLanding(float targetY, const sf::Texture* landedTex, sf::IntRect landedFrame, float landedScale = 1.f) {
        m_isLanding = true;
        m_hasLanded = false;
        m_landingY = targetY;
        m_landedSpriteTex = landedTex;
        m_landedSpriteFrame = landedFrame;
        m_landedSpriteScale = landedScale;
        m_isLandedAnimated = false;
    }

    void setLandingAnimated(float targetY, const sf::Texture* landedTex, const std::vector<sf::IntRect>& landedFrames, float fps, float landedScale = 1.f) {
        m_isLanding = true;
        m_hasLanded = false;
        m_landingY = targetY;
        m_landedSpriteTex = landedTex;
        m_landedSpriteFrames = landedFrames;
        m_landedAnimFps = fps;
        m_landedSpriteScale = landedScale;
        m_isLandedAnimated = true;
    }

    void setHitInterval(float interval) {
        m_hitInterval = interval;
        m_hitIntervalTimer = 0.f;
    }

private:
    struct TrailParticle {
        sf::Vector2f pos;
        float life;
        float maxLife;
        float scale;
    };

    WeaponBase* m_sourceWeapon = nullptr;
    sf::Vector2f m_position;
    sf::Vector2f m_direction;
    sf::Vector2f m_velocity;
    sf::Vector2f m_acceleration;
    float m_damage;
    float m_speed;
    float m_knockbackForce;
    float m_gravity = 0.f;
    float m_spinSpeed = 0.f;
    float m_lifeTimer;
    float m_lifetime;
    bool m_piercing;
    bool m_active;
    bool m_isEnemyProj = false;
    
    float m_maxSpeed = 0.f;
    bool m_bounceOffScreen = false;

    bool m_hasDelayedAccel = false;
    bool m_accelTriggered = false;
    float m_accelTimeLimit = 0.f;
    float m_accelTimer = 0.f;
    sf::Vector2f m_delayedAcceleration;

    bool m_isOrbiting = false;
    sf::Vector2f m_orbitCenter;
    float m_orbitRadius = 0.f;
    float m_orbitAngle = 0.f;
    float m_orbitSpeed = 0.f;

    std::unordered_set<EnemyBase*> m_hitEnemies;

    bool m_isAura = false;
    bool m_isGarlicAura = false;

    sf::CircleShape m_shape;
    sf::RectangleShape m_rectShape;
    bool m_useRect = false;

    AnimatedSprite m_animSprite;
    bool m_hasSprite = false;
    float m_initRotation = 0.f;

    // Santa Water landing state
    bool m_isLanding = false;
    float m_landingY = 0.f;
    bool m_hasLanded = false;
    const sf::Texture* m_landedSpriteTex = nullptr;
    sf::IntRect m_landedSpriteFrame;
    float m_landedSpriteScale = 1.f;
    
    // Animated landing state
    bool m_isLandedAnimated = false;
    std::vector<sf::IntRect> m_landedSpriteFrames;
    float m_landedAnimFps = 8.f;

    float m_hitInterval = -1.f;
    float m_hitIntervalTimer = 0.f;

    // Cached for trail rendering
    const sf::Texture* m_spriteTex  = nullptr;
    sf::IntRect        m_spriteFrame;
    sf::Color          m_spriteColor = sf::Color::White;
    float              m_spriteScale = 1.f;

    // Trail state
    bool  m_trailEnabled  = false;
    float m_trailInterval = 0.04f;
    float m_trailLifetime = 0.2f;
    float m_trailTimer    = 0.f;
    sf::Color m_trailColor = sf::Color::White;
    std::vector<TrailParticle> m_trailParticles;
};
