#pragma once
#include <SFML/Graphics.hpp>
#include <cmath>
#include <vector>
#include <cstdlib>
#include "Engine/AnimatedSprite.h"
#include "Engine/ProfileManager.h"

// A decoupled payload generated by Weapons. Handles its own movement and collision logic.
class Projectile {
public:
    Projectile() : m_active(false), m_damage(0), m_speed(0), m_knockbackForce(0), m_lifeTimer(0), m_lifetime(5.f), m_piercing(false) {}

    void init(const sf::Vector2f& startPos, const sf::Vector2f& direction, float damage, float speed, float range, float lifetime, bool piercing = false) {
        m_position = startPos;
        m_direction = direction;
        
        // Normalize direction
        float length = std::sqrt(m_direction.x * m_direction.x + m_direction.y * m_direction.y);
        if (length > 0) m_direction /= length;
        
        m_speed = speed * ProfileManager::GetInstance().getProjectileSpeedMultiplier();
        m_velocity = m_direction * m_speed;
        m_damage = damage * ProfileManager::GetInstance().getMightMultiplier();
        m_knockbackForce = 0;
        m_lifetime = lifetime * ProfileManager::GetInstance().getDurationMultiplier();
        m_lifeTimer = 0.f;
        m_piercing = piercing;
        m_active = true;
        m_hasSprite = false;
        m_trailEnabled = false;
        m_trailTimer = 0.f;
        m_trailParticles.clear();
        
        float areaMult = ProfileManager::GetInstance().getAreaMultiplier();
        m_shape.setRadius(5.f * areaMult);
        m_shape.setFillColor(sf::Color::Yellow);
        m_shape.setOrigin(5.f * areaMult, 5.f * areaMult);
        m_shape.setPosition(m_position);

        // Store rotation angle — will be applied when sprite is set
        m_initRotation = 0.f;
        if (length > 0) {
            m_initRotation = std::atan2(m_direction.y, m_direction.x) * 180.f / 3.14159f;
        }
    }

    // Set a static sprite frame from an already-loaded texture (shared by weapon)
    void setSprite(const sf::Texture& tex, const sf::IntRect& frame, float scale = 2.f, bool applyRotation = true, sf::Color color = sf::Color::White) {
        m_animSprite.setTexture(tex);
        m_animSprite.setFrames({ frame }, 8.f);
        m_animSprite.setOrigin(frame.width / 2.f, frame.height / 2.f);
        float areaMult = ProfileManager::GetInstance().getAreaMultiplier();
        m_animSprite.setScale(scale * areaMult, scale * areaMult);
        m_animSprite.setColor(color);
        if (applyRotation) m_animSprite.setRotation(m_initRotation);
        m_animSprite.setPosition(m_position);
        m_hasSprite = true;
        m_spriteColor = color;
        m_spriteScale = scale;
        m_spriteFrame = frame;
        m_spriteTex = &tex;
    }

    // Set an animated sprite (multiple frames) for things like the Whip swing
    void setAnimatedSprite(const sf::Texture& tex, const std::vector<sf::IntRect>& frames, float fps, float scale = 2.f) {
        if (frames.empty()) return;
        m_animSprite.setTexture(tex);
        m_animSprite.setFrames(frames, fps);
        m_animSprite.setAutoCenter(true); // Ensure origin is updated as frame sizes change
        m_animSprite.setOrigin(frames[0].width / 2.f, frames[0].height / 2.f);
        float areaMult = ProfileManager::GetInstance().getAreaMultiplier();
        m_animSprite.setScale(scale * areaMult, scale * areaMult);
        m_animSprite.setRotation(m_initRotation);
        m_animSprite.setPosition(m_position);
        m_hasSprite = true;
    }

    // Enable a sparkle trail. `spawnInterval` = seconds between trail particles (e.g. 0.03)
    // `particleLifetime` = how long each particle lives (e.g. 0.25)
    // `color` = trail particle tint
    void enableTrail(float spawnInterval = 0.04f, float particleLifetime = 0.2f, sf::Color color = sf::Color::White) {
        m_trailEnabled    = true;
        m_trailInterval   = spawnInterval;
        m_trailLifetime   = particleLifetime;
        m_trailColor      = color;
        m_trailTimer      = 0.f;
    }

    void update(float dt) {
        if (!m_active) return;
        m_velocity.y += m_gravity * dt;
        m_position += m_velocity * dt;
        
        m_shape.setPosition(m_position);
        if (m_useRect) m_rectShape.setPosition(m_position);
        if (m_hasSprite) {
            if (m_spinSpeed != 0.f) {
                m_initRotation += m_spinSpeed * dt;
                m_animSprite.setRotation(m_initRotation);
            }
            m_animSprite.setPosition(m_position);
            m_animSprite.update(dt);
        }
        
        // Spawn trail particles
        if (m_trailEnabled) {
            m_trailTimer += dt;
            while (m_trailTimer >= m_trailInterval) {
                m_trailTimer -= m_trailInterval;
                TrailParticle tp;
                // Slight random offset around current position
                float ox = ((std::rand() % 100) - 50) * 0.03f;
                float oy = ((std::rand() % 100) - 50) * 0.03f;
                tp.pos      = m_position + sf::Vector2f(ox, oy);
                tp.life     = m_trailLifetime;
                tp.maxLife  = m_trailLifetime;
                tp.scale    = m_spriteScale * 0.6f;   // start at 60% of main sprite scale
                m_trailParticles.push_back(tp);
            }
        }

        // Age and cull trail particles
        for (auto& tp : m_trailParticles) {
            tp.life -= dt;
        }
        m_trailParticles.erase(
            std::remove_if(m_trailParticles.begin(), m_trailParticles.end(),
                [](const TrailParticle& tp){ return tp.life <= 0.f; }),
            m_trailParticles.end());

        m_lifeTimer += dt;
        if (m_lifeTimer >= m_lifetime) {
            m_active = false;
        }
    }

    void draw(sf::RenderWindow& window) {
        if (!m_active) return;

        // Draw trail particles first (behind main sprite)
        if (m_trailEnabled && m_spriteTex && !m_trailParticles.empty()) {
            sf::Sprite trailSprite;
            trailSprite.setTexture(*m_spriteTex);
            trailSprite.setTextureRect(m_spriteFrame);
            trailSprite.setOrigin(m_spriteFrame.width / 2.f, m_spriteFrame.height / 2.f);

            for (const auto& tp : m_trailParticles) {
                float t = tp.life / tp.maxLife;       // 1 = fresh, 0 = dead
                float alpha  = 200.f * t;              // fade out
                float scale  = tp.scale * t;           // shrink as it fades
                
                sf::Color c = m_trailColor;
                c.a = static_cast<sf::Uint8>(std::max(0.f, alpha));

                trailSprite.setColor(c);
                trailSprite.setScale(scale, scale);
                trailSprite.setPosition(tp.pos);
                window.draw(trailSprite, sf::BlendAdd); // additive blending = glowing
            }
        }

        // Draw main projectile
        if (m_hasSprite) {
            m_animSprite.draw(window);
        } else if (m_useRect) {
            window.draw(m_rectShape);
        } else {
            window.draw(m_shape);
        }
    }

    bool isActive() const { return m_active; }
    void deactivate() { m_active = false; }
    bool isPiercing() const { return m_piercing; }
    
    float getDamage() const { return m_damage; }
    float getKnockback() const { return m_knockbackForce; }
    sf::FloatRect getBounds() const { 
        if (m_hasSprite) return m_animSprite.getGlobalBounds();
        if (m_useRect) return m_rectShape.getGlobalBounds();
        return m_shape.getGlobalBounds(); 
    }
    sf::Vector2f getPosition() const { return m_position; }
    sf::Vector2f getDirection() const { return m_direction; }

    void setCustomShape(const sf::Vector2f& size, sf::Color color) {
        // Switch to a rectangle for things like Whip (when no sprite)
        float areaMult = ProfileManager::GetInstance().getAreaMultiplier();
        sf::Vector2f scaledSize = size * areaMult;
        m_rectShape.setSize(scaledSize);
        m_rectShape.setFillColor(color);
        m_rectShape.setOrigin(scaledSize.x / 2.f, scaledSize.y / 2.f);
        m_useRect = true;
    }

    void setGravity(float g) { m_gravity = g; }
    void setSpinSpeed(float s) { m_spinSpeed = s; }

private:
    struct TrailParticle {
        sf::Vector2f pos;
        float life;
        float maxLife;
        float scale;
    };

    sf::Vector2f m_position;
    sf::Vector2f m_direction;
    sf::Vector2f m_velocity;
    float m_damage;
    float m_speed;
    float m_knockbackForce;
    float m_gravity = 0.f;
    float m_spinSpeed = 0.f;
    float m_lifeTimer;
    float m_lifetime;
    bool m_piercing;
    bool m_active;

    sf::CircleShape m_shape;
    sf::RectangleShape m_rectShape;
    bool m_useRect = false;

    AnimatedSprite m_animSprite;
    bool m_hasSprite = false;
    float m_initRotation = 0.f;

    // Cached for trail rendering
    const sf::Texture* m_spriteTex  = nullptr;
    sf::IntRect        m_spriteFrame;
    sf::Color          m_spriteColor = sf::Color::White;
    float              m_spriteScale = 1.f;

    // Trail state
    bool  m_trailEnabled  = false;
    float m_trailInterval = 0.04f;
    float m_trailLifetime = 0.2f;
    float m_trailTimer    = 0.f;
    sf::Color m_trailColor = sf::Color::White;
    std::vector<TrailParticle> m_trailParticles;
};
