#pragma once
#include <SFML/Graphics.hpp>
#include <cmath>

// A decoupled payload generated by Weapons. Handles its own movement and collision logic.
class Projectile {
public:
    Projectile() : m_active(false), m_damage(0), m_speed(0), m_knockbackForce(0), m_lifeTimer(0), m_lifetime(5.f), m_piercing(false) {}

    void init(const sf::Vector2f& startPos, const sf::Vector2f& dir, float damage, float speed, float knockback, float lifetime = 5.f, bool piercing = false) {
        m_position = startPos;
        m_direction = dir;
        
        // Normalize direction
        float length = std::sqrt(m_direction.x * m_direction.x + m_direction.y * m_direction.y);
        if (length > 0) m_direction /= length;

        m_damage = damage;
        m_speed = speed;
        m_knockbackForce = knockback;
        m_lifetime = lifetime;
        m_lifeTimer = 0.f;
        m_piercing = piercing;
        m_active = true;
        
        m_shape.setRadius(5.f);
        m_shape.setFillColor(sf::Color::Yellow);
        m_shape.setOrigin(5.f, 5.f);
        m_shape.setPosition(m_position);
    }

    void update(float dt) {
        if (!m_active) return;
        m_position += m_direction * m_speed * dt;
        m_shape.setPosition(m_position);
        if (m_useRect) m_rectShape.setPosition(m_position);
        
        m_lifeTimer += dt;
        if (m_lifeTimer >= m_lifetime) {
            m_active = false;
        }
    }

    void draw(sf::RenderWindow& window) {
        if (m_active) {
            if (m_useRect) {
                window.draw(m_rectShape);
            } else {
                window.draw(m_shape);
            }
        }
    }

    bool isActive() const { return m_active; }
    void deactivate() { m_active = false; }
    bool isPiercing() const { return m_piercing; }
    
    float getDamage() const { return m_damage; }
    float getKnockback() const { return m_knockbackForce; }
    sf::FloatRect getBounds() const { return m_shape.getGlobalBounds(); }
    sf::Vector2f getPosition() const { return m_position; }
    sf::Vector2f getDirection() const { return m_direction; }

    void setCustomShape(const sf::Vector2f& size, sf::Color color) {
        // Switch to a rectangle for things like Whip
        m_rectShape.setSize(size);
        m_rectShape.setFillColor(color);
        m_rectShape.setOrigin(size.x / 2.f, size.y / 2.f);
        m_useRect = true;
    }

private:
    sf::Vector2f m_position;
    sf::Vector2f m_direction;
    float m_damage;
    float m_speed;
    float m_knockbackForce;
    float m_lifeTimer;
    float m_lifetime;
    bool m_piercing;
    bool m_active;

    sf::CircleShape m_shape;
    sf::RectangleShape m_rectShape;
    bool m_useRect = false;
};
